# Site settings
title: 'Geometry Stash'
email: anson@ansonliu.com
description: > # this means to ignore newlines until "baseurl:"
  Geometry Stash blog and reference
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geometrystash.com" # the base hostname & protocol for your site
twitter_username: ansonvliu
github_username:  ansonl

# Build settings
markdown: kramdown

kramdown:
    input: GFM

#Custom options
permalink:	/:year/:month/:title/
highlighter: pygments
